# NumPy UltraQuick Tutorial

NumPy is a Python library for creating and manipulating vectors and matrices. Coresponding Google Collab tutorial is at https://colab.research.google.com/github/google/eng-edu/blob/master/ml/cc/exercises/numpy_ultraquick_tutorial.ipynb


In [2]:
import numpy as np 

## Populate arrays with specific numbers

Call `np.array` to create a NumPy matrix with your own hand-picked values. For example, the following call to `np.array` creates an 8-element vector:

In [10]:
onedarray = np.array([1,23,4,5])
print(onedarray)

# 2D array 
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

# populate with all zeros 
allzeros = np.zeros((3,2), dtype=int)
print(allzeros)

# populate with all ones 
allones = np.ones((3,2), dtype=int)
print(allones)


[ 1 23  4  5]
[[ 6  5]
 [11  7]
 [ 4  8]]
[[0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]]


In [13]:
# Populate arrays with sequences of numbers

random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

# Random floats 
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[67 98 78 69 87 91]
[0.71082696 0.59525689 0.33439355 0.45940016 0.98485765 0.86443266]


### Mathematical Operations on NumPy Operands

If you want to add or subtract two vectors or matrices, linear algebra requires that the two operands have the same dimensions. Furthermore, if you want to multiply two vectors or matrices, linear algebra imposes strict rules on the dimensional compatibility of operands. Fortunately, NumPy uses a trick called broadcasting https://developers.google.com/machine-learning/glossary/#broadcasting to virtually expand the smaller operand to dimensions compatible for linear algebra. For example, the following operation uses broadcasting to add 2.0 to the value of every item in the vector created in the previous code cell:


In [15]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

# The following operation also relies on broadcasting to multiply each cell in a vector by 3:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[2.71082696 2.59525689 2.33439355 2.45940016 2.98485765 2.86443266]
[201 294 234 207 261 273]


### Task 1: Create a Linear Dataset
Your goal is to create a simple dataset consisting of a single feature and a label as follows:

Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.
Assign 15 values to a NumPy array named label such that:
   label = (3)(feature) + 4
For example, the first value for label should be:

  label = (3)(6) + 4 = 22

In [19]:
# Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.
feature = np.arange(6, 21, dtype=int)
print(feature)

# Assign 15 values to a NumPy array named label such that:
# label = (3)(feature) + 4
label = 3*feature + 4
print(label)



[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


### Task 2: Add Some Noise to the Dataset

To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created. To be more precise, modify each value assigned to label by adding a different random floating-point value between -2 and +2.

Don't rely on broadcasting. Instead, create a noise array having the same dimension as label.

In [20]:
noise = np.random.normal(0, .1, label.shape)
label = label + noise 
print(label)

[21.9293552  25.01439005 27.95017636 30.98997269 34.00524078 37.13928836
 39.92414082 42.95090865 45.93672745 49.03121633 52.13274978 54.86328484
 58.1134519  61.02586309 64.08078877]


### Next steps 

https://numpy.org/devdocs/user/quickstart.html